[tool.poetry]
name = "demisto-sdk"
version = "1.25.3"
description = "\"A Python library for the Demisto SDK\""
authors = ["Demisto"]
license = "MIT"
readme = "README.md"
classifiers=[
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: Implementation :: CPython'
]
exclude = ["TestSuite/**", "*/tests/*", "tests"]

[tool.poetry.scripts]
demisto-sdk = "demisto_sdk.__main__:main"
update-additional-dependencies = "demisto_sdk.scripts.update_additional_dependencies:main"
sdk-changelog = "demisto_sdk.scripts.changelog.changelog:main"
merge-coverage-report = "demisto_sdk.scripts.merge_coverage_report:main"
merge-pytest-reports = "demisto_sdk.scripts.merge_pytest_reports:main"

[tool.poetry.dependencies]
python = ">=3.8,<=3.12"
bandit = "^1.7.7"
mypy = "^1.8.0"
pylint = "^3.0.3"
beautifulsoup4 = "^4.12.3"
chardet = "^5.2.0"
click = "^8.1.7"
coloredlogs = "^15.0.1"
configparser = "^6.0.0"
coverage = "^7.4.1"
decorator = "^5.1.1"
demisto-py = { git = "https://github.com/demisto/demisto-py.git", branch = "support-newer-python-versions" }  # Temporary until demisto-py is updated
dictor = "^0.1.12"
docker = "^7.0.0"
flatten-dict = "^0.4.2"
gitdb = "^4.0.10"
google-cloud-storage = "^2.14.0"
inflection = "^0.5.1"
jsonschema = "^4.21.1"
mergedeep = "^1.3.4"
networkx = "^2.7.1"
nltk = "^3.7"
prettytable = "^3.9.0"
pykwalify = "^1.8.0"
pyspellchecker = "^0.8.1"
requests = "^2.27.1"
"ruamel.yaml" = "^0.17.21"
slack-sdk = "^3.17.0"

tenacity = "^8.2.3"
tabulate = ">=0.8.9,<0.10.0"
ujson = "^5.9.0"
urllib3 = "<2.1.0"  # Can't update to 2.1.0 until demisto-py supports it
wcmatch = "^8.5"
yamlordereddictloader = "^0.4.2"
GitPython = "^3.1.37"
Pebble = ">=4.6.3,<6.0.0"
PyPDF2 = "^1.28.6"
giturlparse = "^0.12.0"
pytest-freezegun = "^0.4.2"
python-dotenv = "^1.0.1"
importlib-resources = "^6.1.1"
dictdiffer = "^0.9.0"
imagesize = "^1.3.0"
cryptography = "<37.0.0"  # Can't update to 37+ until mitmproxy is updated to a version that supports it
dateparser = "^1.2.0"
typed-ast = "^1.5.5"
types-dateparser = "^1.1.4"
types-PyYAML = "^6.0.5"
types-requests = "^2.31.0"
types-pytz = "^2023.3.1"
types-python-dateutil = "^2.8.19"
types-pyvmomi = ">=7.0.6,<9.0.0"
types-tabulate = ">=0.8.6,<0.10.0"
types-paramiko = "^2.8.17"
types-emoji = ">=1.2.7,<3.0.0"
types-ipaddress = "^1.0.8"
types-chardet = ">=4.0.3,<6.0.0"
types-six = "^1.16.12"
types-PyMySQL = "^1.0.15"
typing-extensions = "^4.1.1"
gsutil = {version = "5.17", optional = true}
ordered-set = "^4.1.0"
types-filelock = "^3.2.5"
types-Markdown = "^3.3.21"
types-futures = "^3.3.8"
paramiko = "^2.11.0"
neo4j = "^5.14.0"
pydantic = "^1.10"
types-decorator = "^5.1.8"
types-mock = "^5.1.0"
types-setuptools = "^69.0.0"
types-ujson = "^5.9.0.0"
typer = {extras = ["all"], version = "^0.9.0"}
types-pkg-resources = "^0.1.3"
types-toml = "^0.10.8.7"
packaging = "^23.1"
orjson = "^3.9.12"
more-itertools = "^10.2.0"
junitparser = "^3.1.1"
google-cloud-secret-manager = ">=2.17.0"
json5 = "^0.9.14"
types-protobuf = "^4.24.0"
klara = { version = "^0.6.3", optional = true }



pre-commit = "^3.5.0"
lxml = "^5.0.0"

[tool.poetry.group.dev.dependencies]
mitmproxy = "<8.1.0"  # Versions 8.1.0+ don't support Python 3.8
mock = "^4.0.3"
pytest = "^7.1.1"
pytest-cov = "^4.0.0"
pytest-datadir-ng = "^1.1.1"
pytest-mock = "^3.7.0"
pytest-subprocess = "^1.4.1"
requests-mock = "^1.9.3"
black = "^22.10.0"
ipykernel = "^6.16.1"
ruff = "^0.1.11"
pytest-github-actions-annotate-failures = "^0.2.0"

[tool.poetry.extras]
build = ["gsutil"]
generate-unit-tests = ["klara"]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
python_version = "3.8"
show_error_codes = true
follow_imports = "silent"
pretty = true
allow_redefinition = true
exclude = "tests/.*|demisto_sdk/commands/init/templates/.*"

[tool.vulture]
exclude = ["*/tests/*"]
min_confidence = 80
paths = ["demisto_sdk", "TestSuite"]
sort_by_size = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = [
    "F403",
    "F405",
    "E501",
    "W293",  # handled by Black
]


exclude = [
    "demisto_sdk/tests/test_files/",
    "demisto_sdk/commands/generate_unit_tests/tests/test_files/",
    "demisto_sdk/commands/init/templates",
    "demisto_sdk/commands/generate_yml_from_python/tests/generate_yml_from_python_test.py"
]

select = [
    "C9",
    "E",
    "F",
    "I",
    "PLE",
    "RUF100",
    "T10",
    "T20",
    "TID251",
    "W",
    "PTH107",
    "PTH113",
    "PTH110",
    "PTH119",
]

target-version = "py38"

[tool.ruff.mccabe]
max-complexity = 30

[tool.ruff.flake8-tidy-imports]
[tool.ruff.flake8-tidy-imports.banned-api]
# "logging".msg = "The logging framework is banned. Please use demisto_sdk.commands.common.logger."
"json".msg = "use JSON_Handler instead"
"json5".msg = "use JSON_Handler instead"
"ujson".msg = "use JSON_Handler instead"
"orjson".msg = "use JSON_Handler instead"
"ruamel.yaml".msg = "use YAML_Handler instead"
"distutils.version".msg = "Use packaging.version.Version instead"
"packaging.version.LooseVersion".msg = "Use packaging.version.Version instead"
"git.Repo".msg = "Use GitUtil instead"
