[use_git]
select = ["BA101"]
warning = []
ignorable_errors = ["BA101", "BA116"]

[validate_all]
select = ["BA101"]
warning = []
ignorable_errors = ["BA101", "BA116"]

[Custom_Categories]
select = []
warning = []
ignorable_errors = []


[support_level]

[support_level.community]
ignore = []

[support_level.partner]
ignore = []
