name: Handle New External PRs
on:
  pull_request_target:
    # types: [opened, edited]

permissions:
  pull-requests: write
  repository-projects: read
  contents: read

jobs:
  handle_new_external_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/demisto-sdk' && github.event.pull_request.head.repo.fork == true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_LINK: ${{ github.event.pull_request.html_url }}
          OWNER: ${{ github.owner }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          ./Utils/github_workflow_scripts/handle_external_pr.sh
