name: Handle New External PRs
on:
  pull_request_target:
    # types: [opened, edited]

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  handle_new_external_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/demisto-sdk' && github.event.pull_request.head.repo.fork == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create PR review request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_LINK: ${{ github.event.pull_request_target.html_url }}
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.event.pull_request.head.sha }}
        run: |
          ./Utils/github_workflow_scripts/handle_external_pr.sh
