name: Handle New External PRs
on:
  pull_request_target:
    types: [opened, edited]

permissions: write-all

jobs:
  handle_new_external_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/demisto-sdk' && github.event.pull_request.head.repo.fork == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewers=$(curl -s "https://raw.githubusercontent.com/demisto/content/master/.github/content_roles.json" | jq -r '.CONTRIBUTION_TL')
          echo $reviewers
          gh pr edit ${{ github.event.pull_request.html_url }} --add-assignee $reviewers
          gh pr edit ${{ github.event.pull_request.html_url }} --add-reviewer $reviewers
          echo done
