name: Handle New External PRs
on:
  pull_request_target:
    # types: [opened, edited]

permissions:
  pull-requests: read

jobs:
  handle_new_external_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/demisto-sdk' && github.event.pull_request.head.repo.fork == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_LINK: ${{ github.event.pull_request.html_url }}
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo "Updating External PR ${{ github.event.pull_request.html_url }}"
          cd Utils/github_workflow_scripts
          ./link_pr_to_jira_issue.sh
          echo "Finished Handling External PR"