name: SDK Release
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The PR number'
        required: true
        type: string
      pr_title:
        description: 'The PR title'
        required: true
        type: string
      branch_name:
        description: 'The branch name'
        required: true
        type: string

jobs:
  SDK-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python Environment
        uses: ./.github/actions/setup_environment
        with:
          python-version: "3.11"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch_name }}

      - name: Releasing
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
          PR_TITLE: ${{ inputs.pr_title }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          echo "run releasing for PR: $PR_NUMBER with Name: $PR_TITLE"
          uv run python ./demisto_sdk/scripts/changelog/changelog.py --release -n "$PR_NUMBER" -t "$PR_TITLE" -bn "$BRANCH_NAME"
